Class {
	#name : 'ScopeoInstrumenterFakeTracer',
	#superclass : 'ScopeoInstrumenterTracer',
	#category : 'Scopeo-Instrumenter-',
	#package : 'Scopeo-Instrumenter',
	#tag : ''
}

{ #category : 'tracing' }
ScopeoInstrumenterFakeTracer >> traceAssignment: anArray [

	
]

{ #category : 'tracing' }
ScopeoInstrumenterFakeTracer >> traceMethod: anArray [

	
]

{ #category : 'tracing' }
ScopeoInstrumenterFakeTracer >> traceSend: anArray [

	
]
