Class {
	#name : 'ScpInstrumenterTracerMock',
	#superclass : 'ScpInstrumenterTracer',
	#category : 'Scopeo-Instrumenter-',
	#package : 'Scopeo-Instrumenter',
	#tag : ''
}

{ #category : 'tracing' }
ScpInstrumenterTracerMock >> traceAssignment: anArray [

	
]

{ #category : 'tracing' }
ScpInstrumenterTracerMock >> traceMethod: anArray [

	
]

{ #category : 'tracing' }
ScpInstrumenterTracerMock >> traceSend: anArray [

	
]
